### PR TITLE
Working on release action for master.

### PR DESCRIPTION
**Pull request by tracker1**
- Move Dockerfile to scripts/
- Update README.md, add dockerfile instructions, remove tag from mystic instructions
- Add master.yml workflow to create/update release

NOTE: The dockerhub login will require adding two repository secrets under the Settings->Secrets section in this repository on github.  `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.

It will (re)create a "Latest" release (shown on the right of the main page) with tarballs/zip of the latest from master's built.  As well as publish to Docker Hub for linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6 ... which should cover *most* users of Docker.

### CODE REVIEW

**Comment by echicken** [comment]
This seems fine, but a couple of notes:

I'm following [this template](https://github.com/golang-standards/project-layout) for project structure. The Dockerfile should be in build/package/.

I'd have preferred to keep my build script since it allows me to do a quick local test of the three builds.

I list the 'system_tag' setting but mostly gloss over it at the request of the DoorParty admin. A lot of his documentation involves baking that into the rlogin command line on the BBS side, and he doesn't want to sow confusion.

Merged anyway since none of these are a big deal, but I may rearrange things a bit later.

**Comment by tracker1** [comment]
@echicken the build script is where you left it in `scripts/`, I moved the Dockerfile there as it was most like a build script, and the `build/` output directory was not really necessary with a release action against master in place.

**Comment by echicken** [comment]
Oops! My mistake - I thought I'd left that script in build/. Thanks.

I would probably have left build/package/Dockerfile in place just because that's the suggested location, but it doesn't really matter. For what it does, this project is already overwrought and 90% metadata now.

**Comment by echicken** [comment]
And now having poked around in the project structure a bit more, I've come around to leaving the Dockerfile in scripts/; it makes as much sense as anywhere else.

Okay, I guess we're done here for now.

**Pull request merged**
